[package]
name = "compliance"
version = "0.1.0"
edition = "2018"

[dependencies]
substrate = "3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

### Example for `compliance`
