[package]
name = "alsania_blockchain"
version = "0.1.0"
edition = "2018"

[dependencies]
substrate = "3.0"
libp2p = "0.34"
crystals-dilithium = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
